In [1]:
import numpy as np
from bk_functions import *

In [2]:
test_k_val = generate_scale_invariant_k_points(4,kmin = 0.001, kmax=1.2, n_points_k2 = None)

In [3]:
print(test_k_val)

[[1.00000000e-03 1.20000000e+00 1.00000000e+00]
 [4.00666667e-01 6.67111111e-01 1.00000000e+00]
 [4.00666667e-01 9.33555556e-01 1.00000000e+00]
 [4.00666667e-01 1.20000000e+00 1.00000000e+00]
 [8.00333333e-01 8.00333333e-01 1.00000000e+00]
 [8.00333333e-01 9.33555556e-01 1.00000000e+00]
 [8.00333333e-01 1.06677778e+00 1.00000000e+00]
 [8.00333333e-01 1.20000000e+00 1.00000000e+00]
 [1.20000000e+00 1.20000000e+00 1.00000000e+00]]


In [4]:
np.linspace(1., 1.0, 3)

array([1., 1., 1.])